[package]
name = "repgenerate"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.1"
clap = { version = "4.5.40", features = ["derive"] }
figlet-rs = "0.1.5"
serde = "1.0.219"
serde_json = "1.0.140"
